@startuml
class com.pluralsight.controller.OrderController {
- List<Order> orders
- OrderScreen orderScreen
- SandwichScreen sandwichScreen
- ChipsScreen chipsScreen
- DrinkScreen drinkScreen
- CheckoutScreen checkoutScreen
- Scanner scanner
+ void startNewOrder()
- void confirmOrder(Order)
- void viewOrder(Order)
- void addChips(Order)
+ void viewOrders()
+ void removeOrder()
- void addSandwich(Order)
- void addDrink(Order)
+ void checkout()
}


class com.pluralsight.controller.AppController {
- Scanner scanner
- HomeScreen homeScreen
- OrderController orderController
+ {static} void main(String[])
+ void start()
}


class com.pluralsight.controller.Main {
+ {static} void main(String[])
}

@enduml