@startuml
class com.pluralsight.model.RegularTopping {
- RegularToppingType regularToppingType
+ String toString()
}


class com.pluralsight.model.Meat {
- MeatType meatType
+ String toString()
}


class com.pluralsight.model.Cheese {
- CheeseType cheeseType
+ String toString()
}


enum com.pluralsight.model.enums.RegularToppingType {
+  LETTUCE
+  PEPPERS
+  ONIONS
+  TOMATOES
+  JALEPENOS
+  CUCUMBERS
+  PICKLES
+  GUACAMOLE
+  MUSHROOMS
+  MAYO
+  MUSTARD
+  KETCHUP
+  RANCH
+  THOUSAND_ISLAND
+  VINAIGRETTE
+  AU_JUS
+  SAUCE
}

class com.pluralsight.model.Drink {
- Size size
- Type type
+ String getName()
+ double getPrice()
+ String getSize()
}


enum com.pluralsight.model.Size {
+  SMALL
+  MEDIUM
+  LARGE
- String description
- double price
+ String getDescription()
+ double getPrice()
}


enum com.pluralsight.model.Type {
+  TEA
+  WATER
+  COLA
- String description
+ String getDescription()
}


enum com.pluralsight.model.enums.ChipType {
+  DORITOS
+  LAYS
+  SUN_CHIPS
- String description
+ String getDescription()
}


class com.pluralsight.model.Deli {
- List<Order> orders
+ void addOrder(Order)
+ List<Order> getOrders()
}


enum com.pluralsight.model.enums.BreadType {
+  WHITE
+  WHEAT
+  RYE
+  WRAP
- String description
+ String getDescription()
}


enum com.pluralsight.model.enums.CheeseType {
+  AMERICAN
+  PROVOLONE
+  CHEDDAR
+  SWISS
- String description
+ String getDescription()
}


enum com.pluralsight.model.enums.MeatType {
+  STEAK
+  HAM
+  SALAMI
+  ROAST_BEEF
+  CHICKEN
+  BACON
- String description
+ String getDescription()
}


class com.pluralsight.model.Order {
- List<Product> products
+ void addProduct(Product)
+ double getPrice()
+ void removeProduct(Product)
+ List<Product> getProducts()
}


interface com.pluralsight.model.Priceable {
~ double getPrice()
}

abstract class com.pluralsight.model.Product {
- int quantity
+ {abstract}String getName()
+ int getQuantity()
+ {abstract}double getPrice()
}


class com.pluralsight.model.Chip {
- {static} double CHIP_PRICE
- ChipType chipType
+ String getName()
+ double getPrice()
}


enum com.pluralsight.model.enums.SandwichSize {
+  SMALL
+  MEDIUM
+  LARGE
- String description
+ String getDescription()
}


abstract class com.pluralsight.model.Topping {
- SandwichSize sandwichSize
- ToppingType toppingType
- boolean hasExtra
+ double getPrice()
+ boolean withExtra()
+ ToppingType getToppingType()
+ SandwichSize getSandwichSize()
}


enum com.pluralsight.model.ToppingType {
+  MEAT
+  CHEESE
+  REGULAR
- String description
- double basePrice
- double extraPrice
+ String getDescription()
}




com.pluralsight.model.Topping <|-- com.pluralsight.model.RegularTopping
com.pluralsight.model.Topping <|-- com.pluralsight.model.Meat
com.pluralsight.model.Topping <|-- com.pluralsight.model.Cheese
com.pluralsight.model.Product <|-- com.pluralsight.model.Drink
com.pluralsight.model.Priceable <|.. com.pluralsight.model.Order
com.pluralsight.model.Priceable <|.. com.pluralsight.model.Product
com.pluralsight.model.Product <|-- com.pluralsight.model.Chip
com.pluralsight.model.Priceable <|.. com.pluralsight.model.Topping
@enduml